---
openapi: 3.0.3
info:
 title: user-profile-avatar external service V1
 description: This API provides endpoints to retrieve User Avatars
 version: 1.0.0
servers:
 - url: "http://onecx-user-profile-avatar:8080"
tags:
 - name: avatarExternal
   description: Retrieving User Avatars
paths:
 /v1/avatar/{userId}:
  get:
   security:
    - oauth2: [ ocx-up-avatar:read ]
   tags:
    - avatarExternal
   description: Get the avatar of a user by its id
   operationId: getImage
   parameters:
    - name: userId
      in: path
      required: true
      schema:
       type: string
    - name: refType
      required: true
      in: query
      schema:
       $ref: "#/components/schemas/RefType"
   responses:
    "200":
     description: User Avatar retrieved successfully
     content:
      image/*:
       schema:
        minimum: 1
        maximum: 510000
        type: string
        format: binary
 /v1/avatar/me:
  get:
   security:
    - oauth2: [ ocx-up-avatar:read ]
   tags:
    - avatarExternal
   description: Get the avatar of the requesting user
   operationId: getMyImage
   parameters:
    - name: refType
      required: true
      in: query
      schema:
       $ref: "#/components/schemas/RefType"
   responses:
    "200":
     description: Avatar retrieved successfully
     content:
      image/*:
       schema:
        minimum: 1
        maximum: 510000
        type: string
        format: binary
components:
 securitySchemes:
  oauth2:
   type: oauth2
   flows:
    clientCredentials:
     tokenUrl: https://oauth.simple.api/token
     scopes:
      ocx-up-avatar:read: Grants read access
 schemas:
  RefType:
   type: string
   enum: [ small, medium, large ]
   default: 'medium'